export const currencyByRupee: Currency[] = [
  {
    name: 'DOLLAR',
    value: 0.012271428,
    flag: '🇺🇸',
    symbol: '$',
  },
  {
    name: 'AUSTRALIAN DOLLAR',
    value: 0.015,
    flag: '🇦🇺',
    symbol: '$',
  },
  {
    name: 'BAHAMIAN DOLLAR',
    value: 1,
    flag: '🇧🇸',
    symbol: '$',
  },
  {
    name: 'BARBADIAN DOLLAR',
    value: 0.5,
    flag: '🇧🇧',
    symbol: '$',
  },
  {
    name: 'BELIZE DOLLAR',
    value: 0.5,
    flag: '🇧🇿',
    symbol: '$',
  },
  {
    name: 'BERMUDIAN DOLLAR',
    value: 1,
    flag: '🇧🇲',
    symbol: '$',
  },
  {
    name: 'BRUNEI DOLLAR',
    value: 0.72,
    flag: '🇧🇳',
    symbol: '$',
  },
  {
    name: 'CANADIAN DOLLAR',
    value: 0.78,
    flag: '🇨🇦',
    symbol: '$',
  },
  {
    name: 'CAYMAN ISLANDS DOLLAR',
    value: 1.22,
    flag: '🇰🇾',
    symbol: '$',
  },
  {
    name: 'EAST CARIBBEAN DOLLAR',
    value: 0.37,
    flag: '🇦🇮',
    symbol: '$',
  },
  {
    name: 'EAST CARIBBEAN DOLLAR',
    value: 0.37,
    flag: '🇦🇬',
    symbol: '$',
  },
  {
    name: 'EAST CARIBBEAN DOLLAR',
    value: 0.37,
    flag: '🇩🇲',
    symbol: '$',
  },
  {
    name: 'EAST CARIBBEAN DOLLAR',
    value: 0.37,
    flag: '🇬🇩',
    symbol: '$',
  },
  {
    name: 'EAST CARIBBEAN DOLLAR',
    value: 0.37,
    flag: '🇰🇳',
    symbol: '$',
  },
  {
    name: 'EAST CARIBBEAN DOLLAR',
    value: 0.37,
    flag: '🇱🇨',
    symbol: '$',
  },
  {
    name: 'EAST CARIBBEAN DOLLAR',
    value: 0.37,
    flag: '🇻🇨',
    symbol: '$',
  },
  {
    name: 'FIJIAN DOLLAR',
    value: 0.48,
    flag: '🇫🇯',
    symbol: '$',
  },
  {
    name: 'HONG KONG DOLLAR',
    value: 0.13,
    flag: '🇭🇰',
    symbol: '$',
  },
  {
    name: 'JAMAICAN DOLLAR',
    value: 0.0073,
    flag: '🇯🇲',
    symbol: '$',
  },
  {
    name: 'LIBERIAN DOLLAR',
    value: 0.0052,
    flag: '🇱🇷',
    symbol: '$',
  },
  {
    name: 'NAURUAN DOLLAR',
    value: 0.012,
    flag: '🇳🇷',
    symbol: '$',
  },
  {
    name: 'NEW ZEALAND DOLLAR',
    value: 0.014,
    flag: '🇳🇿',
    symbol: '$',
  },
  {
    name: 'SINGAPORE DOLLAR',
    value: 0.73,
    flag: '🇸🇬',
    symbol: '$',
  },
  {
    name: 'SOLOMON ISLANDS DOLLAR',
    value: 0.12,
    flag: '🇸🇧',
    symbol: '$',
  },
  {
    name: 'SURINAMESE DOLLAR',
    value: 0.000058,
    flag: '🇸🇷',
    symbol: '$',
  },
  {
    name: 'TAIWAN DOLLAR',
    value: 0.035,
    flag: '🇹🇼',
    symbol: '$',
  },
  {
    name: 'TRINIDAD AND TOBAGO DOLLAR',
    value: 0.15,
    flag: '🇹🇹',
    symbol: '$',
  },
  {
    name: 'ZIMBABWEAN DOLLAR',
    value: 0.001,
    flag: '🇿🇼',
    symbol: '$',
  },
];

// [
//   {
//     name: 'US Dollar',
//     value: 10.012271428,
//     flag: '🇺🇸',
//     symbol: '$',
//   },
//   {
//     name: 'Euro',
//     value: 8.551504273,
//     flag: '🇪🇺',
//     symbol: '€',
//   },
//   {
//     name: 'Japanese Yen',
//     value: 110.9834363,
//     flag: '🇯🇵',
//     symbol: '¥',
//   },
//   {
//     name: 'British Pound',
//     value: 7.684823607,
//     flag: '🇬🇧',
//     symbol: '£',
//   },
//   {
//     name: 'Swiss Franc',
//     value: 9.187973493,
//     flag: '🇨🇭',
//     symbol: 'CHF',
//   },
//   {
//     name: 'Canadian Dollar',
//     value: 12.77401907,
//     flag: '🇨🇦',
//     symbol: 'CA$',
//   },
// ];
